### ISSUE TITLE
 org.json.JSONException: No value for Code

### ISSUE THREAD

**Issue by ivalimmb** [xuexiangjys/XHttp2#1]
你好 我这样写
.onMainThread(true)
                .execute(new SimpleCallBack<User>() {
                    @Override
                    public void onSuccess(User response) {
                        Log.e("test","返回的response--->"+response.toString());
                    }
                    @Override
                    public void onError(ApiException e) {
                        Log.e("test","返回的error--->"+e.getDetailMessage());
                    }

                });
然后发生了下面的错误  请问数据格式有要求吗? 不能直接获取一个jsonObject吗? 

org.json.JSONException: No value for Code
2018-08-14 14:51:11.805 24706-24851/org.telegram.biyouchat.beta W/System.err:     at org.json.JSONObject.get(JSONObject.java:389)
2018-08-14 14:51:11.805 24706-24851/org.telegram.biyouchat.beta W/System.err:     at org.json.JSONObject.getInt(JSONObject.java:478)
at com.xuexiang.xhttp2.transform.func.ApiResultFunc.checkApiResult(ApiResultFunc.java:174)

**Comment by xuexiangjys** [comment]
返回的数据必须是下面的格式：
```
{
    "Code":0,
    "Msg":"",
    "Data":{ //数据内容
     }
}
```

**Comment by xuexiangjys** [comment]
Code、Msg、Data必须都是大写

**Comment by xuexiangjys** [comment]
自定义返回体的格式:https://github.com/xuexiangjys/XHttp2#%E8%87%AA%E5%AE%9A%E4%B9%89api%E8%AF%B7%E6%B1%82

**Comment by ivalimmb** [comment]
数据返回格式:
{
status: "1",
message: "OK",
result: "663046792267785498951364"
}

bean实体类:
public class User<T> extends ApiResult<T> {

    private String status;
    private String message;
    private T result;


    @Override
    public int getCode() {
        return Integer.parseInt(status);
    }

    @Override
    public String getMsg() {
        return message;
    }

    @Override
    public boolean isSuccess() {
        return true;
    }

    @Override
    public T getData() {
        return result;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public T getResult() {
        return result;
    }

    public void setResult(T result) {
        this.result = result;
    }
}

请求:
 XHttp.get("/api?module=account&action=balance&address=0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae&tag=latest")
                .execute(new CallBackProxy<User<String>, String>(new TipRequestCallBack<String>() {
                    @Override
                    public void onSuccess(String response) throws Throwable {
                        Log.e("test","返回的response--->"+response.toString());
                    }
                }));

报错:
E/XHttp: --> Subscriber is onError
E/XHttp: --> e instanceof ApiException, message:ApiResult.class.isAssignableFrom(cls) err!!

你好 请问一下这是什么原因呢? 我调试了挺久 看不出问题

**Comment by guodun123** [comment]
使用自定义的ApiResult  需要添加
 -keep class  自定义ApiResult  路径

避免被混淆；在此记录一下 后来人注意
