### ISSUE TITLE
Android 10 download目录权限好像拿不动，更新apk失败

### ISSUE THREAD

**Issue by strivecheng** [xuexiangjys/XHttp2#10]
Android 10 download目录权限好像拿不动，更新apk失败
下载失败!(com.xuexiang.xhttp2.exception.ApiException: java.io.FileNotFoundException: /storage/emulated/0/Download/unknown_version/yzy104.apk: open failed: EACCES (Permission denied))

**Comment by xuexiangjys** [comment]
暂时不要设置下载路径是公共目录,XHttp2还没有适配android10

**Comment by strivecheng** [comment]
> 暂时不要设置下载路径是公共目录,XHttp2还没有适配android10

我降到28版本了，29坑太多，哈哈哈
