### ISSUE TITLE
自定义API请求的话，如果有和默认的json的某个key一样的话，异常：定义多个json字段的exception

### ISSUE THREAD

**Issue by trdmm** [xuexiangjys/XHttp2#11]
其他时候正常，自定义API请求的话，如果有和默认的json的某个key一样的话，
比如服务端返回的是：
```json
{
        "success": true,
        "errorCode": "-1",
        "msg": "登录成功!",
        "body": {xxx}
}
```
会抛出异常`declares multiple JSON fields named msg`。
但如果在自定义的**ApiResult**中不定义**msg**的话，重写父类的`getMsg`方法。如果返回结果`success`为**true**的话，正常调用`onSuccess`；如果返回结果不是`true`，就会走`onError`。抛出**ApiException**，`detailMessage`为`msg`的内容。

不知道是我食用姿势不对还是咋的。

返回其它的的json的话，正常使用。。。。。。

**Comment by trdmm** [comment]
而且像下面这样：
```json
{
         “ success ”：true，
         “ errorCode ”：“ -1 ”，
         “ msg ”：“操作成功！”，
         “ body ”：{
                               xx:xx
                               .......... 
                               xx:{
                                       xxx:xxx
                                   }
                          }
}
```
像这种嵌套的，我body里面获取的都是`null`

**Comment by heqinglin8** [comment]
你是谁？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"同学的可爱女友糖糖"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月10日(星期天) 中午11:25
收件人:&nbsp;"xuexiangjys/XHttp2"<XHttp2@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[xuexiangjys/XHttp2] 自定义API请求的话，如果有和默认的json的某个key一样的话，异常：定义多个json字段的exception (#11)





 
其他时候正常，自定义API请求的话，如果有和默认的json的某个key一样的话，
 比如服务端返回的是：
 {         "success": true,         "errorCode": "-1",         "msg": "登录成功!",         "body": {xxx} }
 
会抛出异常declares multiple JSON fields named msg。
 但如果在自定义的ApiResult中不定义msg的话，重写父类的getMsg方法。如果返回结果success为true的话，正常调用onSuccess；如果返回结果不是true，就会走onError。抛出ApiException，detailMessage为msg的内容。
 
不知道是我食用姿势不对还是咋的。
 
返回其它的的json的话，正常使用。。。。。。

**Comment by xuexiangjys** [comment]
很明显是你的使用姿势不对.我的建议是你还是多看看文档或者源码再考虑自定义api吧,啥都没想明白,干啥呢?依葫芦画瓢不会吗?
https://github.com/xuexiangjys/XHttp2/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89API%E8%AF%B7%E6%B1%82
