### ISSUE TITLE
使用Xhttp2 出现 BEGIN_OBJECT but was BEGIN_ARRAY  错误

### ISSUE THREAD

**Issue by blueflagbj** [xuexiangjys/XHttp2#12]
W/System.err: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 2 column 2 path $

网上搜了一下，发现很多使用 使用RxJava2 + Retrofit2 的都容易出现这样的问题，建议针对这样的问题进行处理，现在找不到处理的地方

**Comment by xuexiangjys** [comment]
和使用RxJava2 + Retrofit2 有半毛钱的关系?
你这英文意思看不懂吗? gson解析的形式不对.本来期待的是object, {}的形式,你跑来个[]形式,数组形式,能解析成功吗???

**Comment by blueflagbj** [comment]
那在哪里修改这个？服务端就只会返回[]形式的数组形式，在哪里处理呢？

**Comment by xuexiangjys** [comment]
你要是真的想让我帮你,就应该把你的问题详细的描述清楚,而不是简单一句怎么处理

**Comment by littlecurl** [comment]
> 那在哪里修改这个？服务端就只会返回[]形式的数组形式，在哪里处理呢？

如果改不了服务端就自定义回调
