### ISSUE TITLE
空值处理方法分享

### ISSUE THREAD

**Issue by senwen-j** [xuexiangjys/XHttp2#14]
分享：由于 rxJava2 不支持空值传递，所以 ApiResult 中 data 为空时会抛异常，所以小弟做了以下修改

![image](https://user-images.githubusercontent.com/58217648/95681055-4f0a0980-0c10-11eb-89a7-794b8acfb78f.png)

位于：com.xuexiang.xhttp2.transform.func.ApiResultFunc

**Comment by senwen-j** [comment]
![image](https://user-images.githubusercontent.com/58217648/95681134-c3dd4380-0c10-11eb-920a-bfda574778b7.png)

**Comment by littlecurl** [comment]
提个 Pull Request 啊，让老薛改一下

**Comment by littlecurl** [comment]
我来提吧
