### ISSUE TITLE
如果服务器端返回的Data字段为null会报“空指针错误”

### ISSUE THREAD

**Issue by marshalys** [xuexiangjys/XHttp2#15]
**问题描述（必填）**
返回格式完全参照：https://github.com/xuexiangjys/XHttp2/wiki/Response%E5%AE%9E%E4%BD%93%E8%A7%84%E8%8C%83 中的标准格式，但是如果服务器端返回的Data字段为null会报“空指针错误”。

**使用的XHttp2版本（必填）**
2.0.0（使用当前最新的 https://github.com/xuexiangjys/TemplateAppProject 模板）

**如何重现（必填）**
重现的步骤:
使用XHttpProxy进行请求，如果服务器端接口返回数组中Data为null则报空指针错误。非null不会有这个错误。

**期望的效果**
Data为null时将对象解析为null，而不是抛出错误。

**Comment by marshalys** [comment]
我查了一下，貌似是因为rxjava2不能nonext传递null值导致的。

**Comment by marshalys** [comment]
看来使用这种方式就不太好解决。

**Comment by littlecurl** [comment]
> 看来使用这种方式就不太好解决。

我也是同样问题，开了个新的issues，可以解决：https://github.com/xuexiangjys/XHttp2/issues/16
但不确定这样解决是否正确。目前来看，好使。
