### ISSUE TITLE
关于ApiResultFunc.parseCustomApiResult()方法有可能造成空指针的问题

### ISSUE THREAD

**Issue by littlecurl** [xuexiangjys/XHttp2#16]
**问题描述（必填）**
有些后端业务，完成之后，data会返回为null，会造成空指针错误。

比如，简单的注册，成功后返回：
{
    code:0，
    msg:"success",
    data:null
}
我在使用的时候，这样会造成空指针错误，Debug半天没找到在哪修改。
后来干脆就在 ApiResultFunc.parseCustomApiResult() 这个方法里，解析完 json 之后，判断一下 data 是否为null，是null 的话，就用 new Object() 代替一下。
```java
 ApiResult result = mGson.fromJson(json, mType);

if (result.getData() == null) {

    result.setData(new Object());

}
```
这样做是否正确？是我代码逻辑错误，还是框架Bug？

**使用的XHttp2版本（必填）**
2.0.0

**如何重现（必填）**
重现的步骤:
1. 后端 data 返回为 null
2. 前端使用 `new SimpleCallBack<Object>(){}` 回调

**期望的效果**
期望回答一下，这样做是否正确？是我代码逻辑错误，还是框架Bug？

**截图**
![image](https://user-images.githubusercontent.com/29348041/98511692-122d4300-22a0-11eb-956f-ac88f611440a.png)

**Comment by xuexiangjys** [comment]
最新版本2.0.1已支持
