### ISSUE TITLE
请更新下三方库支持版本

### ISSUE THREAD

**Issue by lianghao777** [xuexiangjys/XHttp2#18]
implementation 'com.squareup.okhttp3:okhttp:3.10.0'
  implementation 'io.reactivex.rxjava2:rxjava:2.2.0'
  implementation 'io.reactivex.rxjava2:rxandroid:2.1.0'
使用最新的三方库，暴露很多问题哟。

**Comment by xuexiangjys** [comment]
So what‘s your problems?
