### ISSUE TITLE
在自定义Api请求返回结果中如何获取CustomApiResult?

### ISSUE THREAD

**Issue by lsj1937** [xuexiangjys/XHttp2#19]
![image](https://user-images.githubusercontent.com/44017964/107193964-6a541c80-6a2a-11eb-8c8e-dd918e1eb155.png)
如图所示 我想在这个方法中取到自定义的ApiResult中的message信息用来展示Toast
请问有什么方法可以获取呢？

**Comment by xuexiangjys** [comment]
message应该定义的是错误信息,在onError里面获取.如果你是需要成功的提示,建议你还是定义到data里面
