### ISSUE TITLE
请求失败: 首页数据获取成功

### ISSUE THREAD

**Issue by hiliving** [xuexiangjys/XHttp2#2]
`log里看着请求成功了，打印了返回的数据，但是走了OnError()方法。。。用的内置的通用请求，返回数据格式符合要求，Data,Msg,Code

**Comment by xuexiangjys** [comment]
出错请把出错日志信息提供出来，因为onerror不一定是请求出错，只要是请求过程中出现任何错误，都会走到onerror，包括你在请求完成后的代码处理
