### ISSUE TITLE
返回code为String类型，需要怎么操作

### ISSUE THREAD

**Issue by zhaoeryu** [xuexiangjys/XHttp2#21]
**问题描述（必填）**
http接口返回的是String类型的code，需要修改框架中的哪写部分？

**使用的XHttp2版本（必填）**
2.0.2

**期望的效果**
自定义ApiResult，并且code为String类型

**Comment by xuexiangjys** [comment]
先学会看文档,再问可以嘛:

https://github.com/xuexiangjys/XHttp2#%E8%87%AA%E5%AE%9A%E4%B9%89api%E8%AF%B7%E6%B1%82
