### ISSUE TITLE
PUT请求无法被拦截添加请求头的问题

### ISSUE THREAD

**Issue by littlecurl** [xuexiangjys/XHttp2#22]
**问题描述（必填）**
[on 29 Jan 动态拦截器支持请求头的更新](https://github.com/xuexiangjys/XHttp2/commit/2607d768d5767d429450bfd2e7ac8a37559ca054)

BaseDynamicInterceptor 里面只做了对 GET 和 POST 的拦截处理，既然 XHttp2 支持 PUT 和 DELETE ，我认为有必要也做一下拦截，一视同仁。

**使用的XHttp2版本（必填）**
2.0.4（最新版本）

**如何重现（必填）**
重现的步骤:
1. CustomDynamicInterceptor 添加Token，打个断点
2. XHttp.**put**().accessToken(true)
3. 请求时，CustomDynamicInterceptor断点无法进入

**期望的效果**
期望 BaseDynamicInterceptor  中添加对 PUT 和 DELETE 的拦截支持。

**截图**
![image](https://user-images.githubusercontent.com/29348041/121727630-ba4d0800-cb1e-11eb-92e9-d559ebefcfda.png)

**Comment by xuexiangjys** [comment]
可是createNewRequest里面有调用updateHeaders方法啊,为什么没有拦截,我不是很明白?
