### ISSUE TITLE
关于ApiResultFunc  自定义ApiResult 解析时可能存在错误

### ISSUE THREAD

**Issue by thisfeng** [xuexiangjys/XHttp2#24]
在调试时发现 ApiResultFunc 类 apply() 方法，line:74 总是执行自定义  ApiResult 的解析。并且内部解析方法  解析会错误。
走默认ApiResult的解析则 Success ，

``` 
public ApiResult<T> apply(ResponseBody responseBody) throws Exception {
        ApiResult<T> apiResult = new ApiResult<>();
        apiResult.setCode(-1);
        if (mType instanceof ParameterizedType) {
            // 自定义ApiResult
            apiResult = parseCustomApiResult(responseBody, apiResult);
        } else {
            // 默认ApiResult
            apiResult = parseApiResult(responseBody, apiResult);
        }
        return apiResult;
    }
```
  if (mType instanceof ParameterizedType)  这个条件判断 应该 alwasy true 吧？ 不管是使用自定义的那种post 方式， 还是直接使用 XHttp.post() 内部默认的方式。 条件每次都会默认走进这里执行。

tips:
我项目中  code = 1 为成功， 修改了下代码，调试了一番。使用默认 ApiResult 解析逻辑可以解析成功。

比较喜欢你的系列的类库，上手ing

**Comment by xuexiangjys** [comment]
可以直接使用XHttpSDK.setSuccessCode(1)即可
