### ISSUE TITLE
apk打包后的软件，接受后台返回数据为空

### ISSUE THREAD

**Issue by FeiouWang** [xuexiangjys/XHttp2#25]
**问题描述（必填）**
在进行debug的时候程序无异常，但打包为apk，进行安装后，接受返回数据为空

**使用的XHttp2版本（必填）**
2.0.4

**如何重现（必填）**
重现的步骤:
XHttp.post("/user/tet")
                .params("uphone",etPhoneNumber.getText().toString())
                .params("upsd",etVerifyCode.getText().toString())
//                .upJson(JsonUtil.toJson(user))
                .syncRequest(false)
                .execute(new SimpleCallBack<User>() {
                    @Override
                    public void onSuccess(User response) throws Throwable {
                        Util.setUser(response);
                        ActivityUtils.startActivity(MainActivity.class);
                    }
                    @Override
                    public void onError(ApiException e) {
                        XToastUtils.toast("账号或密码错误");
                        System.out.println("Error");
                    }
                });

response 为空

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. 华为P20]
 - Android版本: [e.g. Android 7.0]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by FeiouWang** [comment]
错误代码5010

**Comment by xuexiangjys** [comment]
gson序列化的对象，需要配置代码混淆。不然你就把混淆关闭。
