### ISSUE TITLE
后端使用 sa-token ,安卓如何 获取请求 后的 response header 的 cookie 

### ISSUE THREAD

**Issue by ifnk** [xuexiangjys/XHttp2#27]
如题 ,流程是  获取验证码接口-> 后端响应response 带 header , response header 里面 有 cookie, 然后 我 要把 response 里面 的header 取出来 保存 ，下次请求 要带 cookie ，请问 我用xhttp2 怎样才能拦截 response 请求 并且 找到 里面 的header呢？

**Comment by xuexiangjys** [comment]
加拦截器
