### ISSUE TITLE
Xhttp 请求生命周期绑定

### ISSUE THREAD

**Issue by querli** [xuexiangjys/XHttp2#29]
你好，我阅读了文档，网络请求生命周期和Activity/Fragment生命周期绑定，请问在XHTTP请求中如何使用RxJava的compose的操作符进行绑定？Xhttp请求中无法调用compose函数

**Comment by xuexiangjys** [comment]
正常XHttp请求都可以啊,文档里都有啊,下面是上传的请求,里面就有啊

```
mIProgressLoader.updateMessage("上传中...");
XHttp.post("/book/uploadBookPicture")
        .params("bookId", book.getBookId())
        .uploadFile("file", FileUtils.getFileByPath(mPicturePath), new IProgressResponseCallBack() {
            @Override
            public void onResponseProgress(long bytesWritten, long contentLength, boolean done) {

            }
        }).execute(Boolean.class)
        .compose(RxLifecycle.with(this).<Boolean>bindToLifecycle())
        .subscribeWith(new ProgressLoadingSubscriber<Boolean>(mIProgressLoader) {
            @Override
            public void onSuccess(Boolean aBoolean) {
                mIsEditSuccess = true;
                ToastUtils.toast("图片上传" + (aBoolean ? "成功" : "失败") + "！");
            }
        });
```

**Comment by querli** [comment]
好吧，我使用了execute(CallBack callBack)这个直接返回的是Disposable类型，所以无法绑定生命周期compose函数

**Comment by querli** [comment]
大佬，请问有时间看看下我给你GitHub提issuse吗？确实不知道怎么处理了，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月15日(星期三) 凌晨1:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xuexiangjys/XHttp2] Xhttp 请求生命周期绑定 (Issue #29)





 
正常XHttp请求都可以啊,文档里都有啊,下面是上传的请求,里面就有啊
 mIProgressLoader.updateMessage("上传中..."); XHttp.post("/book/uploadBookPicture")         .params("bookId", book.getBookId())         .uploadFile("file", FileUtils.getFileByPath(mPicturePath), new IProgressResponseCallBack() {             @Override             public void onResponseProgress(long bytesWritten, long contentLength, boolean done) {             }         }).execute(Boolean.class)         .compose(RxLifecycle.with(this).<Boolean&gt;bindToLifecycle())         .subscribeWith(new ProgressLoadingSubscriber<Boolean&gt;(mIProgressLoader) {             @Override             public void onSuccess(Boolean aBoolean) {                 mIsEditSuccess = true;                 ToastUtils.toast("图片上传" + (aBoolean ? "成功" : "失败") + "！");             }         });  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
