### ISSUE TITLE
你好，请问我上传图片如何使用生命周期绑定？

### ISSUE THREAD

**Issue by querli** [xuexiangjys/XHttp2#30]
XHttp.get("/face/statistics")
                .syncRequest(false) //异步请求
                .onMainThread(true)
                //回到主线程
                .execute(object : CallBackProxy<CustomApiResult<FaceInfoBean>, FaceInfoBean>(object :TipRequestCallBack<FaceInfoBean>() {
                    override fun onSuccess(response: FaceInfoBean?) {
                         Log.i("TAG", "请求成功：" + response)

                    }

                }) {})
目前我使用这种方式上传图片是没有问题的，请问如何使用 .compose(RxLifecycle.with(this).bindToLifecycle())方式上传图片，请解答下，谢谢

**Comment by querli** [comment]
就是给上传图片的接口绑定生命周期

**Comment by querli** [comment]
还有我如何去自定义Result中的值？
![image](https://user-images.githubusercontent.com/45426897/147457007-b10472a2-7675-4034-ad05-15bf6e5c372f.png)

**Comment by querli** [comment]
XHttp.post("/book/uploadBookPicture")
            .uploadFile(
                "file", File(path)
            ) { bytesWritten, contentLength, done -> }.execute(CallClazzProxy(CustomApiResult<SportDataBean>()))
            .compose(RxLifecycle.with(this).bindToLifecycle())
            .subscribeWith(object : ProgressLoadingSubscriber<Boolean?>(mLoadingLoader) {
                fun onSuccess(aBoolean: Boolean) {
                    ToastUtils.toast("图片上传" + (if (aBoolean) "成功" else "失败") + "！")
                }

                override fun onSuccess(t: Boolean?) {
                }
            })

请问使用绑定生命周期后如何设置execute(）执行的自定义ApiResult

**Comment by querli** [comment]
还有我看到你讲2.0.1版本已经解决了返回data为null的问题，现在我使用的是2.0.4，返回null，就报api on SubscriberError,我也设置了StrictMode为FALSE，请问这个是怎么解决？

**Comment by xuexiangjys** [comment]
你这种写法暂时不能支持,建议手动处理请求取消
