### ISSUE TITLE
如何同步获取网络请求结果

### ISSUE THREAD

**Issue by BianXiaoming** [xuexiangjys/XHttp2#31]
XHttp.get(baseUrl + "/api/GetDeviceNo")
                .params("imei",imei)
                .keepJson(true)
                .syncRequest(true)
                .execute(String.class)
                .subscribe(new TipRequestSubscriber<String>() {
                    @Override
                    protected void onSuccess(String res) {
                        orderNo = res.replace("\"","");
                        Log.e("GetOrderNo", "onSuccess: orderNo=" + orderNo);
                    }

                    @Override
                    public void onError(ApiException e) {
                        Log.e("GetOrderNo", "onError: ex =" + e.getMessage() );
                    }
                });

报如下错误
W/System.err: android.os.NetworkOnMainThreadException
W/System.err:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1288)

**Comment by xuexiangjys** [comment]
同步你也要保证是在子线程同步,而非主线程同步

**Comment by BianXiaoming** [comment]
理解，谢谢

**Comment by hitanquan** [comment]
兄弟，怎么开启同步请求的？我这么写 syncRequest(true).onMainThread(false) 还是会报错：W/System.err: android.os.NetworkOnMainThreadException
