### ISSUE TITLE
NetMethod能否支持设置hearder参数哈

### ISSUE THREAD

**Issue by zhanghuibiao** [xuexiangjys/XHttp2#34]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XHttp2/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/XHttp2/wiki)，并且确保是框架的问题。

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

----

**问题描述（必填）**
你好，这个框架用着很不错，请问一下NetMethod注解能否支持设置hearder参数呀，有时候需要动态设置头部参数（当然我知道直接调用Xhttp.post().headers("","")这种方式是可以动态设置headers）,只是希望NetMethod注解的这种方式也能支持呢，谢谢

**使用的XHttp2版本（必填）**
2.0.4

**期望的效果**
NetMethod注解的这种方式也能支持设置hearders

**附加信息**
不是bug，只是小小建议哈

**Comment by zhanghuibiao** [comment]
目前发现Xhttp.post().hearder()也是无效的

**Comment by xuexiangjys** [comment]
对于header的处理,我建议还是通过拦截器进行统一的处理

**Comment by zhanghuibiao** [comment]
是的呢，这部最近项目里头遇到部分特殊接口，后端同事非得在hearde中给他们传一些特定参数，就有些难受了，然后我就使用的你i那个针对retrofit的调用方式

**Comment by zhanghuibiao** [comment]
还有个就是最近也是遇到奇葩后台（劝说无用）httpcode返回200，body为null，由于rajava2,onNext()不允许返回null,我就在你那个OnError统一步或json is null的错误来统一处理了,这边能有更好的解决方案吗

**Comment by xuexiangjys** [comment]
使用框架就要按照框架的标准来执行,不然框架没有任何意义
