### ISSUE TITLE
addPostParamsSign

### ISSUE THREAD

**Issue by zhanghuibiao** [xuexiangjys/XHttp2#35]
![image](https://user-images.githubusercontent.com/19171770/153532599-f1c9b438-4db4-45f5-a982-b8046cce5126.png)
private Request addPostParamsSign(Request request) throws UnsupportedEncodingException {
        if (request.body() instanceof FormBody) {
            FormBody.Builder bodyBuilder = new FormBody.Builder();
            FormBody formBody = (FormBody) request.body();

            //原有的参数
            TreeMap<String, Object> oldParams = new TreeMap<>();
            for (int i = 0; i < formBody.size(); i++) {
                oldParams.put(formBody.encodedName(i), formBody.encodedValue(i));
            }

            //拼装新的参数
            TreeMap<String, Object> newParams = updateDynamicParams(oldParams);
            Utils.checkNotNull(newParams, "newParams == null");
            for (Map.Entry<String, Object> entry : newParams.entrySet()) {
                String value = URLDecoder.decode(String.valueOf(entry.getValue()), HttpUtils.UTF8.name());
                bodyBuilder.addEncoded(entry.getKey(), value);
            }
            String url = HttpUtils.createUrlFromParams(HttpUtils.parseUrl(mHttpUrl.url().toString()), newParams);
            HttpLog.i(url);
            formBody = bodyBuilder.build();
            request = createNewRequest(request.newBuilder().post(formBody));
        } else if (request.body() instanceof MultipartBody) {
            MultipartBody multipartBody = (MultipartBody) request.body();
            MultipartBody.Builder bodyBuilder = new MultipartBody.Builder().setType(MultipartBody.FORM);
            List<MultipartBody.Part> oldParts = multipartBody.parts();

            //拼装新的参数
            List<MultipartBody.Part> newParts = new ArrayList<>(oldParts);
            TreeMap<String, Object> oldParams = new TreeMap<>();
            TreeMap<String, Object> newParams = updateDynamicParams(oldParams);
            for (Map.Entry<String, Object> paramEntry : newParams.entrySet()) {
                MultipartBody.Part part = MultipartBody.Part.createFormData(paramEntry.getKey(), String.valueOf(paramEntry.getValue()));
                newParts.add(part);
            }
            for (MultipartBody.Part part : newParts) {
                bodyBuilder.addPart(part);
            }
            multipartBody = bodyBuilder.build();
            request = createNewRequest(request.newBuilder().post(multipartBody));
        } else if (request.body() instanceof RequestBody) {
            TreeMap<String, Object> params = updateDynamicParams(new TreeMap<String, Object>());
            String url = HttpUtils.createUrlFromParams(HttpUtils.parseUrl(mHttpUrl.url().toString()), params);
            request = createNewRequest(request.newBuilder().url(url));
        }
        return request;
    }

URLDecoder.decode 需要修改为URLEncoder.encode

**Comment by xuexiangjys** [comment]
FormBody不需要对内容进行编码

**Comment by zhanghuibiao** [comment]
![image](https://user-images.githubusercontent.com/19171770/153978810-27542c06-587c-406b-92a8-2e691d620940.png)
这种情形我是需要进行encode呢，如果那边不调用encode的话，我得主动调用Uri.encode然后将参数传入呢

**Comment by xuexiangjys** [comment]
我建议你还是自己做处理吧
