### ISSUE TITLE
设置非严格模式不起作用

### ISSUE THREAD

**Issue by lyl12321** [xuexiangjys/XHttp2#36]
**问题描述（必填）**
设置非严格模式后，依然会空指针

**使用的XHttp2版本（必填）**
2.0.4

**如何重现（必填）**
1.XHttp.getInstance().setStrictMode(false);
2.发送一个简单业务请求

**期望的效果**
data:null时不报空指针

**截图**
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/28645315/162347858-8b7382fd-14f8-4aa8-ad8d-75463e0a58a2.png">

**Comment by lyl12321** [comment]
使用CustomRequest就有这样的问题，Xhttp.post xxx之类就不会

**Comment by xuexiangjys** [comment]
使用CustomRequest时, 需重写一下自定义API的setData方法
