### ISSUE TITLE
文件上传在真机上总是报网络请求超时，而模拟器上基本不会

### ISSUE THREAD

**Issue by hitanquan** [xuexiangjys/XHttp2#38]
**问题描述（必填）**

写了个图片上传功能，用到了文件上传，但是在真机上总是报网络请求超时错误，即使设置了超时时间为60s。而模拟器上基本不会有这个问题。希望作者大大帮忙看看👀，感谢

**使用的XHttp2版本（2.04）**

**期望的效果**

不管是真机还是模拟器都能成功上传图片。

**截图**

图片上传代码：

<img width="837" alt="image" src="https://user-images.githubusercontent.com/36075519/165425513-f08ea357-611d-4386-b3a2-94fe96e3f5c9.png">

真机报错：

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/36075519/165425809-d4c808f3-2f47-4a56-bd62-4ebf18be4e8a.png">

模拟器成功上传图片，但是也报这个错：

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/36075519/165426144-8c4432e5-9e5f-4813-ad57-41cca3957f31.png">

**设备信息**
 - 设备名: [小米手机]
 - Android版本: [Android 10.0]

**Comment by xuexiangjys** [comment]
1.模拟器可以，但是真机不行，那是你电脑的防火墙或者地址不对
2.模拟器报的错麻烦你看一下文档再写，你这返回的都什么玩意儿
