### ISSUE TITLE
服务器返回data为“”时，会报“类型转换错误”

### ISSUE THREAD

**Issue by hexin9456** [xuexiangjys/XHttp2#39]
服务器返回data为“”时，会报“类型转换错误”！

**Comment by hexin9456** [comment]
{"code":0,"msg":"success","data":""}

**Comment by xuexiangjys** [comment]
类型不对你写对类型啊...

**Comment by hexin9456** [comment]
服务器有时间时会正常返回类型  没有数据时 就返回这个。。。现在用了不拆包的方法解决了。但是其他的调用 会报 类型转换异常 ！

**Comment by xuexiangjys** [comment]
> 服务器有时间时会正常返回类型 没有数据时 就返回这个。。。现在用了不拆包的方法解决了。但是其他的调用 会报 类型转换异常 ！

所以你想让我怎么帮你，把后台的人拉过来打一顿？
