### ISSUE TITLE
可以画个框架设计图吗

### ISSUE THREAD

**Issue by wangfengye** [xuexiangjys/XHttp2#4]
还有个问题,设计Xhttp.get(url) 这种封装,和直接使用Okhttp提供的请求方式类似, Retrofit将路径和请求解耦,这种哦反向封装有必要吗

**Comment by xuexiangjys** [comment]
这样做的目的是，使用retrofit的特性，但不依赖于retrofit，下层的实现是可以替换掉的，遵循依赖倒置原则

**Comment by xuexiangjys** [comment]
项目uml图已添加，详细参见：779a80b009d92fd8a9737137d91cb83ab679ea42
