### ISSUE TITLE
大佬，能否兼容一下非正常返回的ApiResult中，服务端返回 data 为空字符串的这种情况？或者解决方案 谢谢

### ISSUE THREAD

**Issue by hexin9456** [xuexiangjys/XHttp2#41]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XHttp2/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/XHttp2/wiki)，并且确保是框架的问题。

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

----

**问题描述（必填）**

大佬，能否兼容一下非正常返回的ApiResult中，服务端返回 data 为空字符串的这种情况？
正常的返回都没有问题，框架很完美，但是异常数据 或者空的数据 就会有解析错误的问题！
当然。这不是框架的问题，框架很完美，要是能更好的兼容非正常数据 那就太完美了！

**使用的XHttp2版本（必填）**

最新版本

**如何重现（必填）**
重现的步骤:

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. 华为P20]
 - Android版本: [e.g. Android 7.0]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
使用框架就应该按照框架的规范来，否则框架没有意义。这个不是客户端需要做的
