### ISSUE TITLE
无法解析接收的JSON中字符串格式日期

### ISSUE THREAD

**Issue by suun-icy** [xuexiangjys/XHttp2#45]
在使用XHttp2 POST请求接收JSON数据时，若数据中带有字符串时间，则无法成功

com.github.xuexiangjys:XHttp2:2.0.4

**截图**
![image](https://user-images.githubusercontent.com/53906318/197946440-31edd5cb-3d61-47ad-a486-251d718dd92f.png)
![image](https://user-images.githubusercontent.com/53906318/197946563-d53754d5-4033-4901-bb08-03ce053c8e2f.png)

**设备信息**
IDEA 2021.3.1 模拟器Pixel XL api 24

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
你的json中的日期是string字符串，而非对象，你的对象类型写错了

**Comment by suun-icy** [comment]
我明白，还以为默认可以从String 转为Date类型，现在看来得接收后处理才行，感谢
