### ISSUE TITLE
使用疑問

### ISSUE THREAD

**Issue by thisfeng** [xuexiangjys/XHttp2#47]
**问题描述（必填）**
 再使用过程中， 自定义请求响应的API结构 CustomApiResult ，问我如果想在 执行结果成功 里面，如何能拿到 第一层级里面的 result 字段， 因为 SimpleCallBack  中 传递的类型一般都是 T data ， 的类型。   onSuccess 只能拿到 轉換後的 data 數據。 如何拿到 第一層級的 其它字段？ 
 
<img width="574" alt="image" src="https://github.com/xuexiangjys/XHttp2/assets/16113815/970aaa25-50ab-4f47-b428-6576afec79d7">

**Comment by xuexiangjys** [comment]
通常来说，对于网络框架来说，为了简化使用，所有的成功的数据应该都放在data里面，ApiResult里面只存放msg，code和data这三个数据，保证一个结果输出源。
我的建议是，你把其他字段作为基类，都放到data里面，通过data获取，这样最简单，也最规范。
如果你实在修改不了api的结构，可以使用retrofit的接口定义，调用call，不进行拆包请求。具体可以参考demo中的代码：

https://github.com/xuexiangjys/XHttp2/blob/bb244fb8c851ca83b2fcc8d9dba87f7a29c9c804/xhttp2demo/src/main/java/com/xuexiang/xhttp2demo/fragment/CustomRequestFragment.java#L117C1-L117C1

**Comment by thisfeng** [comment]
感謝回答
确实是的，后台不规范导致。 已经让其建议写入 data 内。
