### ISSUE TITLE
如何显示服务器端返回的httpstate的自定义消息，

### ISSUE THREAD

**Issue by wyp315360007** [xuexiangjys/XHttp2#49]
服务器响应结果：HttpState：401，response body返回下面的内容

{
    "code": 401,
    "data": "用户不存在",
    "message": "Unauthorized"
}

请问如何在UI上面显示这个json里面data属性的消息？
XHttpSDK.setSuccessCode(200); 设置过200了。
拦截器

public class CustomExpiredInterceptor extends BaseExpiredInterceptor {
    @Override
    protected ExpiredInfo isResponseExpired(Response oldResponse, String bodyString) {
        int code = JSONUtils.getInt(bodyString.toLowerCase(), "code", 0);
        ExpiredInfo expiredInfo = new ExpiredInfo(code);
        expiredInfo.setExpiredType(code)
                .setCode(code)
                .setBodyString(bodyString);
        return expiredInfo;
    }
    @SuppressLint("CheckResult")
    @Override
    protected Response responseExpired(Response oldResponse, Chain chain, ExpiredInfo expiredInfo) {
        return HttpUtils.getErrorResponse(oldResponse, expiredInfo.getCode(), expiredInfo.getBodyString());
    }
}

登录操作

 XHttpSDK.postToMain(login).execute(new SimpleCallBack<String>() {
                @Override
                public void onSuccess(String token) throws Throwable {
                    if (!TextUtils.isEmpty(token)) {
                        LoginFragment.super.popToBack();
                        ActivityUtils.startActivity(MainActivity.class);
                    } else {
                        ToasterUtils.error("token没有！");
                    }
                }
                @Override
                public void onError(ApiException e) {
                    ToasterUtils.error(e.getMessage(), 3000);
                    XLog.get().e(e, e.getMessage());
                }
            });

**Comment by xuexiangjys** [comment]
不可以, 框架的定义规则就是: data里的数据只有在成功的时候才有意义, message里的数据只有在失败的时候才有意义.
如果你想在失败(非成功)的时候获取服务器返回的信息,请将有效的信息在message里返回.
