### ISSUE TITLE
不支持直接返回jsonObject格式

### ISSUE THREAD

**Issue by zhanghuibiao** [xuexiangjys/XHttp2#8]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XHttp2/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/XHttp2/wiki)，并且确保是框架的问题。

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

----

**问题描述（必填）**
对问题进行清晰而简明的描述，把握问题的关键点。

**使用的XHttp2版本（必填）**

**如何重现（必填）**
重现的步骤:

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. 华为P20]
 - Android版本: [e.g. Android 7.0]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
本身XHttp2本身的设计就是基于统一返回格式的请求，对于无固定返回格式的请求推荐使用[okhttp-OkGo](https://github.com/jeasonlzy/okhttp-OkGo)或者[使用自定义的retrofit接口](https://github.com/xuexiangjys/XHttp2/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89API%E8%AF%B7%E6%B1%82#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84retrofit%E6%8E%A5%E5%8F%A3)

**Comment by zhanghuibiao** [comment]
{
"Code":0,
"Msg":"",
"Data":{ //数据内容
}
}
先有一种情况是code与msg后台都会返回，而Data返回为null,采用该网络请求框架就会抛异常，像这种data为null的场景还是比较常见的（比如后台出现异常时就会给错误状态码，然后对应的data为null）,希望能够完成对Data为null的容错哈

在 2019-10-17 16:45:02，"薛翔" <notifications@github.com> 写道：


Closed #8.

**Comment by xuexiangjys** [comment]
对于Data为null的情况是没有任何意义的.因为如果请求出错的话,code不为0是不做反序列化的,只会取message字段,Data字段根本不会读取.如果请求成功的话,原则上后端返回规范是不允许出现null的情况的.如果后端不规范出现这种情况的话,可以使用keepjson的形式,不做反序列化
